# Experiment 11
## NumPy Array objects
### a) Program comparing two numpy arrays

In [53]:
import numpy as np

# comparing two arrays
a = np.array([1, 2, 4, 7])
b = np.array([6, 1, 3, 7])

c = a == b
print("a == b:", c)

c = a > b
print("a > b:", c)

c = a <= b
print("a <= b:", c)

a == b: [False False False  True]
a > b: [False  True  True False]
a <= b: [ True False False  True]


In [54]:
# check for boolean values inside arrays
c = a < b
print(np.any(c))
print(np.all(c))

True
False


In [55]:
# logical operations
print(a)
c = np.logical_and(a > 0, a < 4)
print("0 < a < 4:", c)

c = np.logical_or(a >= 0, a == 1)
print("a >= 0 or a == 1:", c)

c = np.logical_not(a)
print("not a:", c)

[1 2 4 7]
0 < a < 4: [ True  True False False]
a >= 0 or a == 1: [ True  True  True  True]
not a: [False False False False]


### b) Program using numpy array attributes like ndim, shape, size, and reshape() and flatten() methods

In [56]:
# numpy arrays of mixed types are not allowed
x = np.array([23, 3.4, 'xyz', True])
print(type(x))
print(x)
print(x.dtype)

<class 'numpy.ndarray'>
['23' '3.4' 'xyz' 'True']
<U32


In [57]:
# slicing
a = np.arange(4, 18)
print(a)

b = a[1:6:2]
print(b)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[5 7 9]


In [58]:
b = a[::]
print(b)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [59]:
b = a[-2:2:-1]
print(b)

[16 15 14 13 12 11 10  9  8  7]


In [60]:
# indexing
print("a:", a)
print("a[0]: ", a[0])
print("a[4]: ", a[4])
print("a[-1]: ", a[-1])
print("a[-3]: ", a[-3])

a: [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17]
a[0]:  4
a[4]:  8
a[-1]:  17
a[-3]:  15


In [61]:
# array dimensions
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
c = np.array([[1, 2], [7, 8], [3, 4], [9, 11]])

print("a: ", a)
print("b: ", b)
print("c: ", c)

a:  [1 2 3 4]
b:  [[1 2]
 [3 4]]
c:  [[ 1  2]
 [ 7  8]
 [ 3  4]
 [ 9 11]]


In [62]:
# ndim
# ndim denotes the rank of the array (e.g. 1D array, 2D array)

print("a.ndim: ", a.ndim)
print("b.ndim: ", b.ndim)
print("c.ndim: ", c.ndim)

a.ndim:  1
b.ndim:  2
c.ndim:  2


In [63]:
# shape
# shape denotes number of elements along each dimension

print("a.shape: ", a.shape)
print("b.shape: ", b.shape)
print("c.shape: ", c.shape)

a.shape:  (4,)
b.shape:  (2, 2)
c.shape:  (4, 2)


In [64]:
# size
# size denotes the total number of elements in an array

print("a.size: ", a.size)
print("b.size: ", b.size)
print("c.size: ", c.size)

a.size:  4
b.size:  4
c.size:  8


In [65]:
# dtype

print("a.dtype", a.dtype)

d = np.array([2.3, 1, 5.6])
print(d)
print(d.dtype)

a.dtype int32
[2.3 1.  5.6]
float64


In [66]:
# reshape() method
arr1 = np.arange(10)
print(arr1)

arr1 = arr1.reshape(2, 5)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
arr2 = arr1.reshape(5, 2)
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [68]:
try:
    arr2 = arr1.reshape(5, 3)
except ValueError as e:
    print(e)

cannot reshape array of size 10 into shape (5,3)


In [69]:
# flatten() method
print(arr2)

arr3 = arr2.flatten()
print(arr3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [70]:
# sorting
# descending order
sorted_arr3 = np.sort(arr3)[::-1]
print(sorted_arr3)
#ascending order
print(np.sort(sorted_arr3))

[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


### c) Program to perform arithmetic operations (addition, subtraction, multiplication, division) on numpy arrays

In [71]:
# numpy arrays
a = np.arange(10)
b = np.arange(0, 20, 2)

print("a:", a)
print("b:", b)

a: [0 1 2 3 4 5 6 7 8 9]
b: [ 0  2  4  6  8 10 12 14 16 18]


In [72]:
c = a + b
print(c)

[ 0  3  6  9 12 15 18 21 24 27]


In [73]:
print(a - b)

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [74]:
print(a / b)

[nan 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


c:\users\chinm\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [75]:
print(a * b)

[  0   2   8  18  32  50  72  98 128 162]


In [76]:
# 2D arrays
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[2,5],[1,3]])

print("m1:", m1)
print("m2:", m2)

m1: [[1 2]
 [3 4]]
m2: [[2 5]
 [1 3]]


In [77]:
print(m1 + m2)

[[3 7]
 [4 7]]


In [78]:
print(m1 - m2)

[[-1 -3]
 [ 2  1]]


In [79]:
print(m1 / m2)

[[0.5        0.4       ]
 [3.         1.33333333]]


In [80]:
print(m1 * m2)

[[ 2 10]
 [ 3 12]]
