# # Experiment 10
## Exploring basics of NumPy Methods
### a) Create numpy arrays using various methods

In [10]:
# import numpy
import numpy as np

In [11]:
# create numpy array using array()
arr1 = np.array([2, 4, 6, 8, 10, 12,14])
print(type(arr1))
print(len(arr1))
print(arr1)

<class 'numpy.ndarray'>
7
[ 2  4  6  8 10 12 14]


In [12]:
# create numpy array using linspace()
# linspace(start, stop, n)
arr2 = np.linspace(5, 15, 6)
print(len(arr2))
print(arr2)

6
[ 5.  7.  9. 11. 13. 15.]


In [13]:
# create numpy array using logspace()
# logspace(start, stop, n)
arr3 = np.logspace(2, 0, 2)
print(len(arr3))
print(arr3)

2
[100.   1.]


In [14]:
# create numpy array using arange()
# arange(start, stop, stepsize)
arr4 = np.arange(3, 33, 3)
print(len(arr4))
print(arr4)

10
[ 3  6  9 12 15 18 21 24 27 30]


In [15]:
# create numpy arrays using zeros() and ones()
arr5 = np.zeros(6)
print(arr5)

arr6 = np.zeros(5, float)
print(arr6)

arr7 = np.zeros(6, int)
print(arr7)

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


In [16]:
arr5 = np.ones(6)
print(arr5)

arr6 = np.ones(6, float)
print(arr6)

arr7 = np.ones(6, int)
print(arr7)

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1]


### b) Find sum, min, max, mean, median, stddev of numpy array

In [17]:
import numpy as np

# create numpy array
int_arr = np.arange(1, 150, 6)
print(int_arr)

print("Sum: ", np.sum(int_arr))
print("Min: ", np.min(int_arr))
print("Max: ", np.max(int_arr))
print("Mean: ", np.mean(int_arr))
print("Median: ", np.median(int_arr))
print("Standard deviation: ", np.std(int_arr))

[  1   7  13  19  25  31  37  43  49  55  61  67  73  79  85  91  97 103
 109 115 121 127 133 139 145]
Sum:  1825
Min:  1
Max:  145
Mean:  73.0
Median:  73.0
Standard deviation:  43.266615305567875


In [18]:
float_arr = np.array([1.69, 2.04, 2.22, 3.45, 3.78])
print(float_arr)

print("Sum: ", np.sum(float_arr))
print("Min: ", np.min(float_arr))
print("Max: ", np.max(float_arr))
print("Mean: ", np.mean(float_arr))
print("Median: ", np.median(float_arr))
print("Standard deviation: ", np.std(float_arr))

[1.69 2.04 2.22 3.45 3.78]
Sum:  13.18
Min:  1.69
Max:  3.78
Mean:  2.636
Median:  2.22
Standard deviation:  0.823956309521324
